name: Github actions

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened

jobs:
  validation-sass:
    name: Validation sass
    uses: alexis-gss/github-workflows/.github/workflows/validation-sass.yml@master
  validation-typescript:
    name: Validation typescript
    uses: alexis-gss/github-workflows/.github/workflows/validation-typescript.yml@master
  validation-php:
    name: Validation php
    uses: alexis-gss/github-workflows/.github/workflows/validation-php.yml@master
  validation-laravel-tests:
    name: Validation Laravel tests
    needs: ['validation-sass', 'validation-typescript', 'validation-php']
    uses: alexis-gss/github-workflows/.github/workflows/validation-laravel-tests.yml@master
  deployment:
    name: Deployment production
    needs: ['validation-sass', 'validation-typescript', 'validation-php', validation-laravel-tests]
    uses: alexis-gss/github-workflows/.github/workflows/deployment.yml@master
    secrets: inherit
    if: github.ref == 'refs/heads/master'
